### PR TITLE
Update Prerequisite for registering domain

### PR DESCRIPTION
**Pull request by longquanzheng**

### CODE REVIEW

**Comment by dmetzgar** [comment]
I take issue with this because we are duplicating documentation. For instance, we don't need the`--gd` flag anymore and now I have to change that in two places.

**Comment by longquanzheng** [comment]
> I take issue with this because we are duplicating documentation. For instance, we don't need the`--gd` flag anymore and now I have to change that in two places.

Makes sense. It will be perfect if I can include some section in the doc site without duplicating it.

**Comment by mfateev** [comment]
Would you update the doc to remove the global flag?

**Comment by longquanzheng** [comment]
> Would you update the doc to remove the global flag?

Done

**Comment by chopincode** [comment]
instructions can be found at https://cadenceworkflow.io/docs/get-started/installation. This PR is deprecated

**Pull request closed without merging**
